### ISSUE TITLE
I got error about cudnnCreate..... COuld you help me out?

### ISSUE THREAD

**Issue by wonchul-kim** [songrotek/DQN-Atari-Tensorflow#6]
I got this below error message:
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce 940MX, pci bus id: 0000:03:00.0)
Could not find old network weights
F tensorflow/stream_executor/cuda/cuda_dnn.cc:222] Check failed: s.ok() could not find cudnnCreate in cudnn DSO; dlerror: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cudnnCreate
Aborted (core dumped)

I definitely installed cudnn and copy it to the right location....

What should I do...?

**Comment by mbrennock** [comment]
I got an error like this one. I'm pretty sure I've installed cudnn correctly - and restarted my system just in case - but it's still not working. Did you figure something out?
